-- MySQL Script generated by MySQL Workbench
-- Wed Mar 26 09:29:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projet72h
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projet72h` ;

-- -----------------------------------------------------
-- Schema projet72h
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projet72h` DEFAULT CHARACTER SET utf8 ;
USE `projet72h` ;

-- -----------------------------------------------------
-- Table `projet72h`.`capteurs_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet72h`.`capteurs_info` ;

CREATE TABLE IF NOT EXISTS `projet72h`.`capteurs_info` (
  `date` INT(16) NOT NULL,
  `capteurs_temp` DECIMAL(20) NOT NULL,
  `capteurs_humide` DECIMAL(20) NOT NULL,
  `capteurs_pbs` INT(1) NULL,
  UNIQUE INDEX `timestamp_UNIQUE` (`date` ASC, `capteurs_temp` ASC, `capteurs_humide` ASC) VISIBLE,
  PRIMARY KEY (`date`),
  UNIQUE INDEX `date_UNIQUE` (`date` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
